name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.9'

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate site
      run: |
        pelican content

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to the bucket
      run: |
        eval $(cat parameters.json | jq -r '.[] | .ParameterKey + "=\"" + .ParameterValue + "\""')
        aws s3 sync ./output s3://fabiangeiger

    - name: Invalidate cloudfront
      if: "contains(github.event.head_commit.message, '/invalidate')"
      run: |
        aws cloudfront create-invalidation --distribution-id EXG0Q039L0H6S --paths "/*"
